version: '3.4'
services:
    app:
        container_name: lango-development-container
        build:
            context: .
            args:
                DOCKER_ENV: development
            dockerfile: ./Dockerfile
        image: laravel-docker-development
        ports:
            - 8000:80
        environment:
            # setting this to local to mimic what we currently have, change?
            APP_ENV: local
            DOCKER_ENV: development
            DB_HOST: mysql
            DB_DATABASE: lango_dump
            DB_USERNAME: langodev
            DB_PASSWORD: secret
            REDIS_HOST: redis
        links:
            - mysql
        networks:
            main:

    mysql:
        image: mariadb/server:10.2.21
        ports:
            - 13306:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: ''
